
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_smsspam_Segment */

#ifndef _Included_com_xiaomi_smsspam_Utils_Tokenizer
#define _Included_com_xiaomi_smsspam_Utils_Tokenizer

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_smsspam_Segment
 * Method:    nativeInitObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xiaomi_smsspam_Utils_Tokenizer_nativeInitObject
  (JNIEnv *, jclass);

/*
 * Class:     com_xiaomi_smsspam_Segment
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_smsspam_Utils_Tokenizer_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_xiaomi_smsspam_Segment
 * Method:    nativeCut
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_xiaomi_smsspam_Utils_Tokenizer_nativeCut
  (JNIEnv *, jclass, jlong, jstring);

JNIEXPORT jboolean JNICALL Java_com_xiaomi_smsspam_Utils_Tokenizer_nativeInDict
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif

#endif

